t1=(4,5,6,7)
a=list(t1)
print("After converting tuple into list : \n")
print(a)
a.insert(4,55)
print("After inserting value in list : \n")
print(a)
x=tuple(a)
print("After converting list into tuple : \n")
print(x)
